# main text of home
name: Raghav Bhasin
bio: '@raghavb95'
# All those who wander are not lost
# if it's an external image, update below for true
external-image: false
picture: 'assets/images/profile.jpg'

url: http://www.raghavbhasin.in
# your url: http://raghavb95.github.io

permalink: /:title/

markdown: kramdown
highlighter: rouge

# To enable google analytics, supply your token below
analytics-google: 'UA-59933281-2'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, set to false Else mydisqus
disqus: false

# if you don't have any of social below, comment the line
facebook: raghavb95
twitter: raghavb95
# google: mygoogle
instagram: raghavb95
# pinterest: mypinterest
linkedin: raghavb95
youtube: raghavb95
# spotify: myspotify
github: raghavb95
# medium: medium

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: true

# if you don't need "about" or "blog", comment them out below
about: true
# blog: true

# do you want to show the "read time" of the posts?
# read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
# related: true

# do you want some animations?
animation: true

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, indigo-gh-pages.zip, Rakefile, screen-shot.png, travis.sh]
